add class adress_book
DenysTantsiura/pva pull request #4
Opened 2022-12-22 14:21 UTC by armandabasi

2022-12-22 15:22 UTC, DenysTantsiura requested changes
Супер, чудово, може таки зразу щось будемо трошки коригувати?

2022-12-22 15:22 UTC, DenysTantsiura commented on address_book.py
> +    """Class of Address Book """
Десь чув що в закордонних компаніях дуже полюбляють крапки в кінці речень (щодо докстрінгів).

2022-12-22 15:22 UTC, DenysTantsiura commented on address_book.py
> +    def __str__(self) -> str:
В нас тут не обов'язково, мабуть взагалі прибрати цей метод __str__

2022-12-22 15:22 UTC, DenysTantsiura commented on address_book.py
> +        now_day = datetime.now()
Головне що б не доводилось час народження крім дати вводити та опрацьовувати :)

2022-12-22 15:22 UTC, DenysTantsiura commented on address_book.py
> +                b_day = contact.birthday.value
Ментор не робив зауваження щодо назв змінних? зручно і зрозуміло нам, але можна подумати bad day, або bee day. Так, шось не уловив алгоритм, тут в нашій книзі дані лише для поточного року? Тобто в записах всі народилися поточного року? Або, наприклад, сьогодні 22.12.2022, ДН 25.12.2000, то days_for_b_day буде < 0? Значить наступна дата буде в наступному році 25.12.2023 і не виведе що через 3 дні, бо буде рік+3 дні? Треба перепровірити, точно працює вірно?

2022-12-22 15:22 UTC, DenysTantsiura commented on address_book.py
> +        i = 0
Ця і=0... може зразу перейменувати в каунтер якийсь?

2022-12-22 15:22 UTC, DenysTantsiura commented on address_book.py
> +            yield page
Тобто без StopIteration працює? І після останньої частинки якщо ще раз 10 звернутись то 10 раз буде виводити повтори останньої частинки? Треба перепровірити і пофіксити, якщо треба, чи потім в процесі першого запуску?

2022-12-22 15:29 UTC, armandabasi commented on address_book.py
> +                b_day = contact.birthday.value
Тут я перероблю. 
Я хочу з Record додати функцію, яка в нас була в дз, днів до дня народження. І якщо днів до дня народження меньше чим заданих днів то цей контакт додавати до списку

2022-12-22 15:39 UTC, armandabasi commented on address_book.py
> +            yield page
Тут я теж допрацюю) поки складно дебажити, не маючи можливості запустити код)

2022-12-23 13:36 UTC, DenysTantsiura approved these changes
Все одно треба буте розкоментувати, відкоригувати...

2022-12-23 13:36 UTC, DenysTantsiura commented on address_book.py
> +    """Class of Address Book """
"""Class of Address Book """
"""Class of Address Book."""
мабуть ж

2022-12-23 13:36 UTC, DenysTantsiura commented on address_book.py
> +    #def iterator(self, n_count: int) -> list:
То... нащо закоменчено? 
і===== limit_counter
наприклад

2022-12-23 13:36 UTC, merged