Created the class Note for a single note.
DenysTantsiura/pva pull request #7
Opened 2022-12-22 22:43 UTC by syaya123

Created the metods: __str__, add_tags and change_note.
In the module class_note the bot initializes an object of the Notes class and creates list of tags; adds a new tag or tags to list of tags and also takes into account the limit of the number of tags; rewrites note or changes some words in the note.

2022-12-22 23:31 UTC, DenysTantsiura requested changes
Чудово, трошки підправити і обговорити...

2022-12-22 23:31 UTC, DenysTantsiura commented on .vscode/launch.json
> +{
Це зайвий файл, до нашої програми не відноситься, він для роботи ВСКода, в ГІТХАБ-десктопі його можна виключити для відстежування і він не потраплятиме більше до ГІТа.

2022-12-22 23:31 UTC, DenysTantsiura commented on class_note.py
> +        The bot takes into account the limit of the number of tags.
Ліміт? Який? і звідки бере? Чи треба додати і додаватиметься? Ага нижче бачу константне значення 5

2022-12-22 23:31 UTC, DenysTantsiura commented on class_note.py
> +        add_tags = new_tags.split(', ')
ну, якщо так, то так, треба буде десь повідомляти як, можна вводити і через пробіл, і через кому безпробілу...

2022-12-22 23:31 UTC, DenysTantsiura commented on class_note.py
> +        number_tags = 5
Якщо не будемо вводити, і не змінюватиметься, то константи всі в апперкейсах, всі великі літери, начебто ж так було?

2022-12-22 23:31 UTC, DenysTantsiura commented on class_note.py
> +                        return ('This tag already exists!')
Отуто ми в циклі, і при першому тезі в обох випадках(чи вже є чи ще немає такого тегу) ретюрн - зупинить цикл, тобто лише перший з декількох оброблюватиметься. Можна просто принтити

2022-12-22 23:31 UTC, DenysTantsiura commented on class_note.py
> +                        self.tags.append(', '.join(add_tags))
self.tags.append(', '.join(add_tags))   тобто до спискутегів примірника self.tags додаємо СТРОКУ! в якій о'бєднуються елементи введеного списку, на кожній ітерації циклу (якщо без зупинки ретютном).
Тобто якщо всі нові теги - додаємо їх і повертаємо - все Ок, якщо хоч один тег вже занесений раніше - зупиняємо цикл і не перевіряємо наступні, бо ретюрним 'This tag already exists!', так і задумувалось?
Чи може додавати по одному тегу до списку, як окремі елементи?

2022-12-22 23:31 UTC, DenysTantsiura commented on class_note.py
> +    def change_note(self, changed_text, new_text) -> tuple:
значить повертає не тапл, виправити, і
примушувати користувача вводити весь текст великої нотатки, якщо він бажає її змінити... може трошки інакше зробити, прінтити тест старої нотатки і хай вводить новий текст для неї, якщо якісь зміни є, бо це не зміна а заміна в нотатках виходить. Можна обговорити на міті.

2022-12-23 06:52 UTC, DenysTantsiura commented
Так, УВАЖНІШЕ! пише що хоче залиавати запит на main гілку, а треба в dev

2022-12-23 11:46 UTC, syaya123 commented on .vscode/launch.json
> +{
Видалю пізніше.

2022-12-23 11:51 UTC, syaya123 commented on class_note.py
> +        add_tags = new_tags.split(', ')
Треба буде вибрати, можна й через #

2022-12-23 13:16 UTC, DenysTantsiura approved these changes

2022-12-23 13:16 UTC, merged