BuPCSCk7/create note book.py
DenysTantsiura/pva pull request #8
Opened 2022-12-22 23:07 UTC by Belzer104

Add class NoteBook
Add method add_record
Add method iterator
Add method remove_record
Add method sort_by_tags

2022-12-22 23:43 UTC, DenysTantsiura requested changes

2022-12-22 23:43 UTC, DenysTantsiura commented on note_book.py
> +        for record in self.data.values():
Тобто без StopIteration працює? І після останньої частинки якщо ще раз 10 звернутись то 10 раз буде виводити повтори останньої частинки? Треба перепровірити і пофіксити, якщо треба, чи потім в процесі першого запуску?

2022-12-22 23:43 UTC, DenysTantsiura commented on note_book.py
> +            i += 1
і... може зразу назвати змінну АйКаунтер якийсь?

2022-12-22 23:43 UTC, DenysTantsiura commented on note_book.py
> +        self.data.pop(name)
працює, я теж так робив, лишаємо, чи краще через del зробити?

2022-12-23 00:20 UTC, Belzer104 commented on note_book.py
> +        for record in self.data.values():
Я думаю в процесі пофіксимо

2022-12-23 00:22 UTC, Belzer104 commented on note_book.py
> +            i += 1
Зараз виправлю

2022-12-23 06:38 UTC, DenysTantsiura approved these changes

2022-12-23 06:38 UTC, merged